### ISSUE TITLE
Blank page when logging in

### ISSUE THREAD

**Issue by auino** [inovector/mixpost#124]
### Detailed description

After installing Mixpost through Docker, when logging in with the default `admin@example.com:changeme` account, a blank page is returned and no feedback is provided.
Also, nothing relevant is found on the container's logs.

**Comment by lao9s** [comment]
Hi @auino 
Try to enable dub mode with `APP_DEBUG: true`env variable.

**Comment by auino** [comment]
Thanks @lao9s.
Tried and nothing changes, also looking at the logs.

**Comment by lao9s** [comment]
@auino 
Please, share the `docker-compose.yml` and `.env` file (make sure you hide the sensitive data).

**Comment by auino** [comment]
Here is the `docker-compose.yml` file content:

```
services:
    mixpost:
        image: inovector/mixpost:latest
        env_file:
            - .env
        ports:
            - 9000:80
        volumes:
            - storage:/var/www/html/storage/app
            - logs:/var/www/html/storage/logs
        depends_on:
            - mysql
            - redis 
        restart: unless-stopped
    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: mystrongpassword
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: "%"
        volumes:
            - 'mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p ${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
        restart: unless-stopped
    redis:
        image: 'redis:latest'
        command: redis-server --appendonly yes --replica-read-only no
        volumes:
            - 'redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        restart: unless-stopped  

volumes:
    mysql:
        driver: local
    redis:
        driver: local
    storage:
        driver: local
    logs:
        driver: local
```

and `.env` file content (please also note that `example.com` redirects to `localhost` in my `/etc/hosts` local file:

```
# The name of your application.
APP_NAME=Mixpost

# Key used to encrypt and decrypt sensitive data. Generate this using the following tool:
# https://mixpost.app/tools/encryption-key-generator
APP_KEY=base64:<omitted>

# Debug mode setting. Set to `false` for production environments.
APP_DEBUG=true

# Your app's domain or subdomain, without the 'http://' or 'https://' prefix.
APP_DOMAIN=example.com

# Full application URL is automatically configured; no modification required.
APP_URL=http://${APP_DOMAIN}:9000

# MySQL connection setup.
DB_DATABASE=mixpost_db
DB_USERNAME=mixpost_user
DB_PASSWORD=mystrongpassword

# Specify the email address to be used for SSL certificate registration and notifications.
SSL_EMAIL=user@example.com
```
