### ISSUE TITLE
Cron triggering error: Command `mixpost:prune-temporary-directory` is not defined

### ISSUE THREAD

**Issue by neil-lcv-cs** [inovector/mixpost#137]
### Steps to reproduce the problem

Hi,

On a fresh Mixpost v2.1.2 Docker install, I’m having this error in Laravel logs every hour:

```
[2025-03-02 11:00:05] production.ERROR: Command "mixpost:prune-temporary-directory" is not defined.

Did you mean one of these?
    mixpost-auth:create
    mixpost-auth:delete
    mixpost-auth:password
    mixpost:clear-services-cache
    mixpost:clear-settings-cache
    mixpost:create-mastodon-app
    mixpost:delete-old-data
    mixpost:import-account-audience
    mixpost:import-account-data
    mixpost:process-metrics
    mixpost:publish
    mixpost:publish-assets
    mixpost:run-scheduled-posts
    mixpost:setup-gitignore
    mixpost:update-migration-timestamps {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"mixpost:prune-temporary-directory\" is not defined.

Did you mean one of these?
    mixpost-auth:create
    mixpost-auth:delete
    mixpost-auth:password
    mixpost:clear-services-cache
    mixpost:clear-settings-cache
    mixpost:create-mastodon-app
    mixpost:delete-old-data
    mixpost:import-account-audience
    mixpost:import-account-data
    mixpost:process-metrics
    mixpost:publish
    mixpost:publish-assets
    mixpost:run-scheduled-posts
    mixpost:setup-gitignore
    mixpost:update-migration-timestamps at /var/www/html/vendor/symfony/console/Application.php:726)
[stacktrace]
#0 /var/www/html/vendor/symfony/console/Application.php(284): Symfony\\Component\\Console\\Application->find()
#1 /var/www/html/vendor/symfony/console/Application.php(193): Symfony\\Component\\Console\\Application->doRun()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(198): Symfony\\Component\\Console\\Application->run()
#3 /var/www/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#4 {main}
"} 
```

Seems like a bundled cron is attempting to run a deprecated command. May be linked to #131 ?

### Expected behaviour

No error logs.

### Actual behaviour

Error logs.

### Detailed description

```yml
services:
  mixpost:
    image: inovector/mixpost:v2.1.2
    env_file:
      - .env
    volumes:
      - mixpost-storage-v2:/var/www/html/storage/app
      - mixpost-logs-v2:/var/www/html/storage/logs
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    networks:
      mixpost-net:
        ipv4_address: 172.21.X.X
  mysql:
    image: 'mariadb:10.11'
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mysql-data-v2:/var/lib/mysql
    restart: unless-stopped
    networks:
      mixpost-net:
        ipv4_address: 172.21.X.X
  redis:
    image: 'redis:latest'
    command: redis-server --appendonly yes --replica-read-only no
    volumes:
      - redis-data-v2:/data
    restart: unless-stopped
    networks:
      mixpost-net:
        ipv4_address: 172.21.X.X
volumes:
  mysql-data-v2:
    external: true
  redis-data-v2:
    external: true
  mixpost-storage-v2:
    external: true
  mixpost-logs-v2:
    external: true
networks:
  mixpost-net:
    external: true
```

### Specifications

Debian Bookworm 6.1.0-31-amd64
Docker CE 27.5.1
Mixpost 2.1.2
MariaDB 10.11
Redis 7.4.2

```
# php artisan about
  Environment ......................................................................................................................................
  Application Name ......................................................................................................................... Mixpost
  Laravel Version .......................................................................................................................... 11.43.2
  PHP Version ............................................................................................................................... 8.3.17
  Composer Version ........................................................................................................................... 2.8.5
  Environment ........................................................................................................................... production
...
```
