### ISSUE TITLE
deployment through Portainer does not work

### ISSUE THREAD

**Issue by plasticpippo** [inovector/mixpost#151]
### Steps to reproduce the problem

1.installed via portainer and kept getting error 500
2.in the logs i could not see password created for admin@example.com - env variables were correctly entered in the Portainer Stack
3.installed via command line docker compose and it worked
...

### Expected behaviour

should be working with portainer installation

### Actual behaviour

Mixpost docker service could not create password for admin access

### Detailed description

just an additional note. i have tried running the service through Pangolin (https://github.com/fosrl/pangolin) but any click on the mixpost webpage did not do anything. Also despite having an SSL cert issued but pangolin with traefik i was getting error: the password is not protected by SSL cert and could be interepted by third party

### Specifications

mixpost latest version pulled through docker
Brave Browser Version 1.77.100 Chromium: 135.0.7049.100 (Official Build) (64-bit)](https://brave.com/latest/)
Mozilla Firefox 137.0.2 (64-bit)

**Comment by Novapixel1010** [comment]
I am also having the same issue 

# compose file

```yaml

services:
    mixpost:
        image: inovector/mixpost:latest
        ports:
            - 5000:80
        volumes:
            - storage:/var/www/html/storage/app
            - logs:/var/www/html/storage/logs
        depends_on:
            - mysql
            - redis
        restart: unless-stopped
        environment:

            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_PORT: 6379

    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - 'mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_PASSWORD}"]
            retries: 3
            timeout: 5s
        restart: unless-stopped

    redis:
        image: 'redis:latest'
        command: redis-server --appendonly yes --replica-read-only no
        volumes:
            - 'redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped  

volumes:
    mysql:
        driver: local
    redis:
        driver: local
    storage:
        driver: local
    logs:
        driver: local
```

# my env

```
APP_NAME=Mixpost
APP_KEY=IYuSeuvsdvrqo68VJH0Y8OCGuN0MbgoM5cvVr9wwwnc=
APP_DEBUG=false
APP_DOMAIN=post.in.com
APP_URL=https://${APP_DOMAIN}
DB_DATABASE=mixpost_db
DB_USERNAME=mixpost_user
DB_PASSWORD=whatiwant
SSL_EMAIL=user@in.com
```

My proxy is caddy

portainer: 2.21.1

**Comment by Novapixel1010** [comment]
Got it working with putting the env variables in compose @plasticpippo 

```yaml
services:
    mixpost:
        image: inovector/mixpost:latest
        ports:
            - 5000:80
        volumes:
            - storage:/var/www/html/storage/app
            - logs:/var/www/html/storage/logs
        depends_on:
            - mysql
            - redis
        restart: unless-stopped
        environment:
         APP_NAME: Mixpost
         APP_KEY: base64:IYuSeuvsdvrqo68VJH0Y8OCGuN0MbgoM5cvVr9wwwnc=
         APP_DEBUG: true
         APP_DOMAIN: post.in.com
         APP_URL: http://localhost:5000   # <--- fix here for now
         DB_CONNECTION: mysql
         DB_HOST: mysql
         DB_PORT: 3306
         DB_DATABASE: mixpost_db
         DB_USERNAME: mixpost_user
         DB_PASSWORD: whatiwant
         REDIS_HOST: redis
         REDIS_PORT: 6379


    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_DATABASE: mixpost_db
            MYSQL_USER: mixpost_user
            MYSQL_PASSWORD: whatiwant
        volumes:
            - 'mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_PASSWORD}"]
            retries: 3
            timeout: 5s
        restart: unless-stopped

    redis:
        image: 'redis:latest'
        command: redis-server --appendonly yes --replica-read-only no
        volumes:
            - 'redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped  

volumes:
    mysql:
        driver: local
    redis:
        driver: local
    storage:
        driver: local
    logs:
        driver: local
```
