### ISSUE TITLE
Error uploading mp4 media

### ISSUE THREAD

**Issue by 81reap** [inovector/mixpost#63]
### Steps to reproduce the problem

1. Run `docker compose`
2. Create new post
3. Try to upload a mp4 file
4. fail

### Expected behaviour

.mp4 file should upload

### Actual behaviour

it failed

### Detailed description

Images seem to upload fine but videos [[EXAMPLE](https://file-examples.com/storage/fe19e15eac6560f8c936c41/2017/04/file_example_MP4_480_1_5MG.mp4)] fail. I see no logs for mixpost nor from cloudflared that would indicate that the network failed.

### Specifications

```
[reap@apollo docker]$ cat mixpost.yml 
version: '3.1'

services:
    # admin@example.com // changeme
    mixpost:
        image: inovector/mixpost:latest
        environment:
            APP_NAME: 'Mixpost'
            APP_KEY: base64:Yt7UPpH71ABdT31NAGjPZkqOGbmjgGekbLR8HRIBZ7k=
              # Generate a base64 secret with this tool: https://mixpost.app/encryption-key-generator
            APP_URL: https://example.com
            DB_DATABASE: 'example_db_name'
            DB_USERNAME: 'example_db_user'
            DB_PASSWORD: 'example_db_password'
        ports:
            - 89:80
        volumes:
            - mixpost-storage:/var/www/html/storage/app
            - mixpost-logs:/var/www/html/storage/logs
        depends_on:
            - mysql
            - redis 
        restart: unless-stopped
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'example_db_name'
            MYSQL_USER: 'example_db_user'
            MYSQL_PASSWORD: 'example_db_password'
        volumes:
            - 'mixpost-mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p example_db_password"]
            retries: 3
            timeout: 5s
        restart: unless-stopped
    redis:
        image: 'redis:6.2.11'
        command: redis-server --appendonly yes --replica-read-only no --protected-mode no
        ports:
          - '6379:6379'
        volumes:
            - 'mixpost-redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        restart: unless-stopped  
volumes:
    mixpost-mysql:
        driver: local
    mixpost-redis:
        driver: local
    mixpost-storage:
        driver: local
    mixpost-logs:
        driver: local
```
