### ISSUE TITLE
Cannot get past the login screen.  "Internal Error"

### ISSUE THREAD

**Issue by TxTechnician** [inovector/mixpost#83]
### Steps to reproduce the problem

I've installed MixPost using Docker on my Synology NAS.  And am using Nginx to serve the site.

I try to login to MixPost.  And after about 3 minutes the login will time out and give me an error message "Internal Error".  
![image](https://github.com/inovector/mixpost/assets/113131384/50975cf4-a3de-47ef-8432-d0044158ad11)

Here is the setup files I have:

# NGINX config
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name mixpostdelete.REMOVED THE DOMAIN NAME FOR THIS POST.com ;

    if ( $host !~ "(^mixpostdelete.REMOVED THE DOMAIN NAME FOR THIS POST.com$)" ) { return 404; }

    include /usr/syno/etc/www/certificate/ReverseProxy_7dbb39fd-0a77-4718-9c8b-7dc9509cd700/cert.conf*;

    include /usr/syno/etc/security-profile/tls-profile/config/ReverseProxy_7dbb39fd-0a77-4718-9c8b-7dc9509cd700.conf*;

    proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    location / {

        proxy_connect_timeout 60;

        proxy_read_timeout 60;

        proxy_send_timeout 60;

        proxy_intercept_errors off;

        proxy_http_version 1.1;

        proxy_set_header        Host            $http_host;

        proxy_set_header        X-Real-IP            $remote_addr;

        proxy_set_header        X-Forwarded-For            $proxy_add_x_forwarded_for;

        proxy_set_header        X-Forwarded-Proto            $scheme;

        proxy_pass http://localhost:9000;

    }

    error_page 403 404 500 502 503 504 /dsm_error_page;

    location /dsm_error_page {
        internal;
        root /usr/syno/share/nginx;
        rewrite (.*) /error.html break;
        allow all;
    }

}
```

# Docker Compose.yml
```
version: '3.1'

services:
    mixpost:
        image: inovector/mixpost:latest
        environment:
            APP_NAME: 'Mixpost'
            APP_KEY: base64:O/9jBHK3kJ16GDfVfVcwucJ7BWNems4oB1B+IJdudlw= # Generate a base64 secret with this tool: https://mixpost.app/encryption-key-generator
            APP_URL: https://mixpostdelete.REMOVED THE DOMAIN FOR THIS POST.com
            DB_DATABASE: 'mixpost_delete_db'
            DB_USERNAME: 'mixpost_delete_user'
            DB_PASSWORD: 'mixpost_delete_password'
        ports:
            - 9000:80
        volumes:
            - mixpost-storage:/var/www/html/storage/app
            - mixpost-logs:/var/www/html/storage/logs
        depends_on:
            - mysql
            - redis 
        restart: unless-stopped
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'mixpost_delete_db'
            MYSQL_USER: 'mixpost_delete_user'
            MYSQL_PASSWORD: 'mixpost_delete_password'
        volumes:
            - 'mixpost-mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p mixpost_delete_password"]
            retries: 3
            timeout: 5s
        restart: unless-stopped
    redis:
        image: 'redis:latest'
        command: redis-server --appendonly yes --replica-read-only no
        volumes:
            - 'mixpost-redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        restart: unless-stopped  
volumes:
    mixpost-mysql:
        driver: local
    mixpost-redis:
        driver: local
    mixpost-storage:
        driver: local
    mixpost-logs:

```

# Startup of docker container from terminal:

```
root@Synology:/volume1/docker/mixpostdelete# docker-compose up
[+] Running 4/4
 ⠿ Network mixpostdelete_default      Created                                                                                   1.1s
 ⠿ Container mixpostdelete-redis-1    Created                                                                                   1.1s
 ⠿ Container mixpostdelete-mysql-1    Created                                                                                   1.0s
 ⠿ Container mixpostdelete-mixpost-1  Created                                                                                   0.6s
Attaching to mixpostdelete-mixpost-1, mixpostdelete-mysql-1, mixpostdelete-redis-1
mixpostdelete-mysql-1    | [Entrypoint] MySQL Docker Image 8.0.32-1.2.11-server
mixpostdelete-redis-1    | 1:C 08 Mar 2024 18:16:56.603 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
mixpostdelete-redis-1    | 1:C 08 Mar 2024 18:16:56.603 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
mixpostdelete-redis-1    | 1:C 08 Mar 2024 18:16:56.603 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
mixpostdelete-redis-1    | 1:C 08 Mar 2024 18:16:56.603 * Configuration loaded
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.603 * monotonic clock: POSIX clock_gettime
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 * Running mode=standalone, port=6379.
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 * Server initialized
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 * Reading RDB base file on AOF loading...
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 * Loading RDB produced by version 7.2.4
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 * RDB age 3017 seconds
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 * RDB memory usage when created 0.83 Mb
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 * RDB is base AOF
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 * Done loading RDB, keys loaded: 0, keys expired: 0.
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 * DB loaded from base file appendonly.aof.1.base.rdb: 0.000 seconds
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 * DB loaded from append only file: 0.000 seconds
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:16:56.604 * Ready to accept connections tcp
mixpostdelete-mysql-1    | [Entrypoint] Starting MySQL 8.0.32-1.2.11-server
mixpostdelete-mysql-1    | 2024-03-08T18:16:56.857568Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
mixpostdelete-mysql-1    | 2024-03-08T18:16:56.858622Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.32) starting as process 1
mixpostdelete-mysql-1    | 2024-03-08T18:16:56.936658Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mixpostdelete-mysql-1    | 2024-03-08T18:17:00.685671Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mixpostdelete-mixpost-1  | 
mixpostdelete-mixpost-1  |    INFO  Configuration cached successfully.  
mixpostdelete-mixpost-1  | 
mixpostdelete-mixpost-1  | 
mixpostdelete-mixpost-1  |    INFO  Application cache cleared successfully.  
mixpostdelete-mixpost-1  | 
mixpostdelete-mixpost-1  | 
mixpostdelete-mixpost-1  |    INFO  Routes cached successfully.  
mixpostdelete-mixpost-1  | 
mixpostdelete-mixpost-1  |  * Starting periodic command scheduler cron
mixpostdelete-mixpost-1  |    ...done.
mixpostdelete-mixpost-1  | Mixpost has started!
mixpostdelete-mixpost-1  | 2024-03-08 18:17:04,582 INFO Set uid to user 0 succeeded
mixpostdelete-mixpost-1  | 2024-03-08 18:17:04,587 INFO supervisord started with pid 22
mixpostdelete-mixpost-1  | 2024-03-08 18:17:05,589 INFO spawned: 'mixpost_horizon_00' with pid 24
mixpostdelete-mixpost-1  | 2024-03-08 18:17:05,590 INFO spawned: 'nginx' with pid 25
mixpostdelete-mixpost-1  | 2024-03-08 18:17:05,591 INFO spawned: 'php-fpm' with pid 26
mixpostdelete-mixpost-1  | 2024-03-08 18:17:06,839 INFO success: mixpost_horizon_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
mixpostdelete-mixpost-1  | 2024-03-08 18:17:06,839 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
mixpostdelete-mixpost-1  | 2024-03-08 18:17:06,839 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
mixpostdelete-mysql-1    | 2024-03-08T18:17:07.117702Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mixpostdelete-mysql-1    | 2024-03-08T18:17:07.117735Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mixpostdelete-mysql-1    | 2024-03-08T18:17:07.172778Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
mixpostdelete-mysql-1    | 2024-03-08T18:17:07.172952Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.32'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  MySQL Community Server - GPL.
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:21:57.001 * 100 changes in 300 seconds. Saving...
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:21:57.001 * Background saving started by pid 73
mixpostdelete-redis-1    | 73:C 08 Mar 2024 18:21:57.419 * DB saved on disk
mixpostdelete-redis-1    | 73:C 08 Mar 2024 18:21:57.419 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:21:57.502 * Background saving terminated with success
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:26:58.055 * 100 changes in 300 seconds. Saving...
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:26:58.055 * Background saving started by pid 135
mixpostdelete-redis-1    | 135:C 08 Mar 2024 18:26:58.493 * DB saved on disk
mixpostdelete-redis-1    | 135:C 08 Mar 2024 18:26:58.493 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:26:58.556 * Background saving terminated with success
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:31:59.093 * 100 changes in 300 seconds. Saving...
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:31:59.093 * Background saving started by pid 196
mixpostdelete-redis-1    | 196:C 08 Mar 2024 18:31:59.509 * DB saved on disk
mixpostdelete-redis-1    | 196:C 08 Mar 2024 18:31:59.509 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
mixpostdelete-redis-1    | 1:M 08 Mar 2024 18:31:59.598 * Background saving terminated with success
```

### Expected behaviour

I should be able to login to continue the setup of mixpost

### Actual behaviour

can't login, get an internal error message.

### Specifications

![image](https://github.com/inovector/mixpost/assets/113131384/ae3c5043-55be-44fb-8251-09cdacdd2764)
